name: Build and Run GetStarted example
on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: Arm-Virtual-Hardware
    env:
      ARMLMD_LICENSE_FILE: /opt/data.dat
      ARM_TOOL_VARIANT: ult
      AC6_TOOLCHAIN_6_18_0: /opt/armcompiler/bin
      LD_LIBRARY_PATH: /opt/VHT
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache vcpkg
        uses: actions/cache@v3
        with:
          key: vcpkg
          path: /home/runner/.vcpkg

      - name: Cache packs
        uses: actions/cache@v3
        with:
          key: packs
          path: /home/runner/.cache/arm/packs

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: cpp
          queries: security-and-quality
      - name: Build the example
        run: |
          . <(curl https://aka.ms/vcpkg-init.sh -L)
          vcpkg activate
          cbuild get_started.csolution.yml --packs --update-rte --configuration .debug+vht

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

      - name: Run the example
        run: |
          /opt/VHT/VHT_MPS2_Cortex-M3 -f vht-config.txt -a hello/out/hello/debug/vht/debug+vht.elf